URL_SERVICE = "https://97acd3ec-6f30-44db-a389-9ff00cfa3275.serverhub.praktikum-services.ru/"
COURIER_LOGIN = "/api/v1/courier/login"
CURIER_CREATE = "/api/v1/courier"
CREATE_NEW_ORDER = "/api/v1/orders"
RECEIVING_ORDER_BY_ID = "/api/v1/orders/track"